### ISSUE TITLE
Error: Cannot find module '@workshop/server'

### ISSUE THREAD

**Issue by jrweinb** [stackgl/webgl-workshop#49]
Hello,

After installing the npm module, I try to run the app with "webgl-workshop" and I get the following error after typing Yes for populating the directory:

```
module.js:340
    throw err;
          ^
Error: Cannot find module '@workshop/server'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at boot (/usr/local/lib/node_modules/webgl-workshop/node.js:49:3)
    at PromptUI.completed (/usr/local/lib/node_modules/webgl-workshop/node.js:44:5)
    at PromptUI.onCompletion (/usr/local/lib/node_modules/webgl-workshop/node_modules/inquirer/lib/ui/prompt.js:51:10)
    at /usr/local/lib/node_modules/webgl-workshop/node_modules/inquirer/node_modules/async/lib/async.js:254:17
    at /usr/local/lib/node_modules/webgl-workshop/node_modules/inquirer/node_modules/async/lib/async.js:157:25
    at /usr/local/lib/node_modules/webgl-workshop/node_modules/inquirer/node_modules/async/lib/async.js:251:21
```

**Comment by Jsgoller1** [comment]
I got almost exactly the same error message, but on Linux (uname -a: Linux computer 3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
). Solved it by cloning locally, using make, and then running the node.js file.

**Comment by ezekeal** [comment]
same issue

**Comment by msfeldstein** [comment]
Perhaps we should remove the instructions to install globally if that doesn't seem to work for most people (including me)?

**Comment by LeeeRoux** [comment]
Same issue,
 Windows 8.1
Node `8.11.1`
Npm `6.4.1`

**Comment by keli95566** [comment]
same issue
Mac
Node 14.0.0
Npm 6.4.1
