### ISSUE TITLE
webgl-workshop error

### ISSUE THREAD

**Issue by rk08** [stackgl/webgl-workshop#61]
Hi,

After doing npm install -g webgl-workshop I ran webgl-workshop. I am getting the error below. Can you guys tell me how to fix it.

C:\Users\Desktop\node-school\webgl-advanced> webgl-workshop

 ==============================
 = ~~~~~ webgl-workshop ~~~~~ =
 ==============================

[?] We're about to populate this directory with some code for you to use for
    your answers. If they've already been created then don't worry, they won't
    be replaced. Continue? Yes

module.js:340
    throw err;
          ^
Error: Cannot find module '@workshop/server'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at boot (C:\Users\AppData\Roaming\npm\node_modules\webgl-workshop\node.js:49:3)
    at PromptUI.completed (C:\Users\AppData\Roaming\npm\node_modules\webgl-workshop\node.js:44:5)
    at PromptUI.onCompletion (C:\Users\AppData\Roaming\npm\node_modules\webgl-workshop\node_modules\inquirer\lib\ui\prompt.js:51:10)
    at C:\Users\AppData\Roaming\npm\node_modules\webgl-workshop\node_modules\inquirer\node_modules\async\lib\async.js:254:17
    at C:\Users\AppData\Roaming\npm\node_modules\webgl-workshop\node_modules\inquirer\node_modules\async\lib\async.js:157:25
    at C:\Users\AppData\Roaming\npm\node_modules\webgl-workshop\node_modules\inquirer\node_modules\async\lib\async.js:251:21
C:\Users\Desktop\node-school\webgl-advanced>

**Comment by serapath** [comment]
I have the same problem - and it's already one year old - that doesnt sound very promising
