### ISSUE TITLE
intro-hello-webgl broken

### ISSUE THREAD

**Issue by winduptoy** [stackgl/webgl-workshop#72]
Seems like an update to [gl-matrix](https://github.com/toji/gl-matrix) has broken the intro lesson, making `mat4` undefined on line 9 of `draw-bunny.js`.

**Comment by xoryouyou** [comment]
The intro still seems to be broken

I am getting this error when opening `http://localhost:14921/@exercise/intro-hello-webgl/`

```
/usr/lib/node_modules/webgl-workshop/node_modules/brfs/node_modules/quote-stream/index.js:70
                if (rawBuf.equals(multiByteBuffers.lineSeparator)) {
                           ^
TypeError: Object – has no method 'equals'
    at DestroyableTransform.write [as _transform] (/usr/lib/node_modules/webgl-workshop/node_modules/brfs/node_modules/quote-stream/index.js:70:28)
    at DestroyableTransform.Transform._read (/usr/lib/node_modules/webgl-workshop/node_modules/brfs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:10)
    at DestroyableTransform.Transform._write (/usr/lib/node_modules/webgl-workshop/node_modules/brfs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:160:12)
    at doWrite (/usr/lib/node_modules/webgl-workshop/node_modules/brfs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:326:12)
    at writeOrBuffer (/usr/lib/node_modules/webgl-workshop/node_modules/brfs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:312:5)
    at DestroyableTransform.Writable.write (/usr/lib/node_modules/webgl-workshop/node_modules/brfs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:239:11)
    at write (_stream_readable.js:602:24)
    at flow (_stream_readable.js:611:7)
    at ReadStream.pipeOnReadable (_stream_readable.js:643:5)
    at ReadStream.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
webgl-workshop  18,25s user 2,33s system 31% cpu 1:05,24 total
```

`webgl-workshop@1.1.0 /usr/lib/node_modules/webgl-workshop`  installed via `npm install -g webgl-workshop`

on node 0.10.37

**Comment by tbarber350** [comment]
I am getting the same error as xoryouyou

**Comment by hughsk** [comment]
@winduptoy @xoryouyou @tbarber350 I believe this has been fixed as of the latest version — could you try again and let me know how it goes? Apologies for the delay :)

**Comment by xoryouyou** [comment]
@hughsk also sorry for the late reply but just checkout out the repo and it works like a charm now :)
