### ISSUE TITLE
EMFILE, too many open files

### ISSUE THREAD

**Issue by hackingbeauty** [stackgl/webgl-workshop#73]
After starting the program with the command "webgl-workshop", and clicking on the first exercise "HELLO, WEBGL" , I'm getting the following stack track:

fs.js:438
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: EMFILE, too many open files '/usr/local/lib/node_modules/webgl-workshop/node_modules/glslify/node_modules/glslify-stream/node_modules/through/index.js'
    at Object.fs.openSync (fs.js:438:18)
    at Object.fs.readFileSync (fs.js:289:15)
    at Object.Module._extensions..js (module.js:473:44)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/webgl-workshop/node_modules/glslify/node_modules/glslify-stream/index.js:7:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

Am I doing something wrong?

**Comment by jeffscottward** [comment]
Seeing the same. Help?

**Comment by mpmckenna8** [comment]
Getting the same error here.

**Comment by mattdesl** [comment]
Perhaps related thread with solutions:
https://github.com/substack/node-browserify/issues/431
