### ISSUE TITLE
Unable to install on windows

### ISSUE THREAD

**Issue by dfcreative** [stackgl/webgl-workshop#85]
During the installation `npm install -g webgl-workshop` there are loads of errors of a kind:
```
...
npm ERR! addLocal Could not install C:\Users\dmitry\AppData\Roaming\npm\node_modules\webgl-workshop\workshop\menu
npm WARN install Couldn't install optional dependency: ENOENT: no such file or directory, open 'C:\Users\dmitry\AppData\
Roaming\npm\node_modules\webgl-workshop\workshop\menu'
npm ERR! addLocal Could not install C:\Users\dmitry\AppData\Roaming\npm\node_modules\webgl-workshop\workshop\server
npm WARN install Couldn't install optional dependency: ENOENT: no such file or directory, open 'C:\Users\dmitry\AppData\
Roaming\npm\node_modules\webgl-workshop\workshop\server'
npm ERR! addLocal Could not install C:\Users\dmitry\AppData\Roaming\npm\node_modules\webgl-workshop\workshop\server-basi
c
npm WARN install Couldn't install optional dependency: ENOENT: no such file or directory, open 'C:\Users\dmitry\AppData\
Roaming\npm\node_modules\webgl-workshop\workshop\server-basic'
```
After which the process is just abrupted with no additional info.

Attempting to install it locally `npm install webgl-workshop` takes somewhat longer, asks password to github in betweem, but ends with no success:
```
...
npm WARN install Couldn't install optional dependency: ENOENT: no such file or directory, open 'c:\Users\dmitry\Dropbox\
Projects\gl-experiment\node_modules\webgl-workshop\workshop\server'
npm ERR! addLocal Could not install c:\Users\dmitry\Dropbox\Projects\gl-experiment\node_modules\webgl-workshop\workshop\
server-basic
npm WARN install Couldn't install optional dependency: ENOENT: no such file or directory, open 'c:\Users\dmitry\Dropbox\
Projects\gl-experiment\node_modules\webgl-workshop\workshop\server-basic'
npm WARN install Couldn't install optional dependency: Unsupported
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
npm WARN deprecated find-file@0.1.4: Use the globby package instead
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:213:12)
npm WARN addRemoteGit     at emitTwo (events.js:87:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:172:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:818:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:319:11)
npm WARN addRemoteGit     at emitOne (events.js:77:13)
npm WARN addRemoteGit     at Socket.emit (events.js:169:7)
npm WARN addRemoteGit     at Pipe._onclose (net.js:469:12)
npm WARN addRemoteGit  pipobscure/fsevents#7dcdf9fa3f8956610fd6f69f72c67bace2de7138 resetting remote C:\Users\dmitry\App
Data\Roaming\npm-cache\_git-remotes\git-github-com-pipobscure-fsevents-git-7dcdf9fa3f8956610fd6f69f72c67bace2de7138-7b0f
3a17d1f9029adb4a98ef988cf38f because of error: { [Error: Command failed: git -c core.longpaths=true config --get remote.
origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
npm ERR! git clone --template=C:\Users\dmitry\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.co
m/pipobscure/fsevents.git C:\Users\dmitry\AppData\Roaming\npm-cache\_git-remotes\git-github-com-pipobscure-fsevents-git-
7dcdf9fa3f8956610fd6f69f72c67bace2de7138-7b0f3a17d1f9029adb4a98ef988cf38f: Cloning into bare repository 'C:\Users\dmitry
\AppData\Roaming\npm-cache\_git-remotes\git-github-com-pipobscure-fsevents-git-7dcdf9fa3f8956610fd6f69f72c67bace2de7138-
7b0f3a17d1f9029adb4a98ef988cf38f'...
npm ERR! git clone --template=C:\Users\dmitry\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.co
m/pipobscure/fsevents.git C:\Users\dmitry\AppData\Roaming\npm-cache\_git-remotes\git-github-com-pipobscure-fsevents-git-
7dcdf9fa3f8956610fd6f69f72c67bace2de7138-7b0f3a17d1f9029adb4a98ef988cf38f:
npm ERR! git clone --template=C:\Users\dmitry\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.co
m/pipobscure/fsevents.git C:\Users\dmitry\AppData\Roaming\npm-cache\_git-remotes\git-github-com-pipobscure-fsevents-git-
7dcdf9fa3f8956610fd6f69f72c67bace2de7138-7b0f3a17d1f9029adb4a98ef988cf38f: fatal: unable to overwrite old ref-pack file:
 Is a directory
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:213:12)
npm WARN addRemoteGit     at emitTwo (events.js:87:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:172:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:818:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
npm WARN addRemoteGit  pipobscure/fsevents#7dcdf9fa3f8956610fd6f69f72c67bace2de7138 resetting remote C:\Users\dmitry\App
Data\Roaming\npm-cache\_git-remotes\git-https-github-com-pipobscure-fsevents-git-7dcdf9fa3f8956610fd6f69f72c67bace2de713
8-d5669a67d907288290e1e1a94bb0eabb because of error: { [Error: Command failed: git -c core.longpaths=true config --get r
emote.origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
npm ERR! git clone --template=C:\Users\dmitry\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.
com/pipobscure/fsevents.git C:\Users\dmitry\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-pipobscure-fseve
nts-git-7dcdf9fa3f8956610fd6f69f72c67bace2de7138-d5669a67d907288290e1e1a94bb0eabb: Cloning into bare repository 'C:\User
s\dmitry\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-pipobscure-fsevents-git-7dcdf9fa3f8956610fd6f69f72c
67bace2de7138-d5669a67d907288290e1e1a94bb0eabb'...
npm ERR! git clone --template=C:\Users\dmitry\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.
com/pipobscure/fsevents.git C:\Users\dmitry\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-pipobscure-fseve
nts-git-7dcdf9fa3f8956610fd6f69f72c67bace2de7138-d5669a67d907288290e1e1a94bb0eabb:
npm ERR! git clone --template=C:\Users\dmitry\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.
com/pipobscure/fsevents.git C:\Users\dmitry\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-pipobscure-fseve
nts-git-7dcdf9fa3f8956610fd6f69f72c67bace2de7138-d5669a67d907288290e1e1a94bb0eabb: fatal: Fetch attempted without a loca
l repo
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:213:12)
npm WARN addRemoteGit     at emitTwo (events.js:87:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:172:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:818:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
npm WARN addRemoteGit  pipobscure/fsevents#7dcdf9fa3f8956610fd6f69f72c67bace2de7138 resetting remote C:\Users\dmitry\App
Data\Roaming\npm-cache\_git-remotes\git-github-com-pipobscure-fsevents-git-7dcdf9fa3f8956610fd6f69f72c67bace2de7138-ed28
052b25864b3d5529276bb4593169 because of error: { [Error: Command failed: git -c core.longpaths=true config --get remote.
origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
loadDep:fsevents → git    ▐ ╢█████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
npm ERR! git clone --template=C:\Users\dmitry\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:
pipobscure/fsevents.git C:\Users\dmitry\AppData\Roaming\npm-cache\_git-remotes\git-github-com-pipobscure-fsevents-git-7d
cdf9fa3f8956610fd6f69f72c67bace2de7138-ed28052b25864b3d5529276bb4593169: Cloning into bare repository 'C:\Users\dmitry\A
ppData\Roaming\npm-cache\_git-remotes\git-github-com-pipobscure-fsevents-git-7dcdf9fa3f8956610fd6f69f72c67bace2de7138-ed
28052b25864b3d5529276bb4593169'...
npm ERR! git clone --template=C:\Users\dmitry\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:
pipobscure/fsevents.git C:\Users\dmitry\AppData\Roaming\npm-cache\_git-remotes\git-github-com-pipobscure-fsevents-git-7d
cdf9fa3f8956610fd6f69f72c67bace2de7138-ed28052b25864b3d5529276bb4593169:
npm ERR! git clone --template=C:\Users\dmitry\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:
pipobscure/fsevents.git C:\Users\dmitry\AppData\Roaming\npm-cache\_git-remotes\git-github-com-pipobscure-fsevents-git-7d
cdf9fa3f8956610fd6f69f72c67bace2de7138-ed28052b25864b3d5529276bb4593169: fatal: unable to overwrite old ref-pack file: I
s a directory
npm WARN install Couldn't install optional dependency: Command failed: git -c core.longpaths=true clone --template=C:\Us
ers\dmitry\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:pipobscure/fsevents.git C:\Users\dm
itry\AppData\Roaming\npm-cache\_git-remotes\git-github-com-pipobscure-fsevents-git-7dcdf9fa3f8956610fd6f69f72c67bace2de7
138-ed28052b25864b3d5529276bb4593169
npm WARN install fatal: unable to overwrite old ref-pack file: Is a directory
npm WARN install
npm WARN ENOENT ENOENT: no such file or directory, open 'c:\Users\dmitry\Dropbox\Projects\gl-experiment\package.json'
npm WARN EPACKAGEJSON gl-experiment No description
npm WARN EPACKAGEJSON gl-experiment No repository field.
npm WARN EPACKAGEJSON gl-experiment No README data
npm WARN EPACKAGEJSON gl-experiment No license field.
```
Node version 5.3.0, npm version 3.3.12, windows 7 x64.

**Comment by hughsk** [comment]
@dfcreative could you please try again and let me know if it's working after the latest publish? Thanks! :D

**Comment by dfcreative** [comment]
@hughsk well it installs now, but then:
```sh
C:\Users\dmitry\Dropbox\Projects\gl-experiment\webgl-workshop-test>webgl-workshop

 ==============================
 = ~~~~~ webgl-workshop ~~~~~ =
 ==============================

[?] We're about to populate this directory with some code for you to use for
    your answers. If they've already been created then don't worry, they won't
    be replaced. Continue? Yes

readline.js:925
            throw err;
            ^

Error: Cannot find module '@workshop/server'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at boot (C:\Users\dmitry\AppData\Roaming\npm\node_modules\webgl-workshop\node.js:49:3)
    at PromptUI.completed (C:\Users\dmitry\AppData\Roaming\npm\node_modules\webgl-workshop\node.js:44:5)
    at PromptUI.onCompletion (C:\Users\dmitry\AppData\Roaming\npm\node_modules\webgl-workshop\node_modules\inquirer\lib\
ui\prompt.js:51:10)
    at C:\Users\dmitry\AppData\Roaming\npm\node_modules\webgl-workshop\node_modules\inquirer\node_modules\async\lib\asyn
c.js:254:17
    at C:\Users\dmitry\AppData\Roaming\npm\node_modules\webgl-workshop\node_modules\inquirer\node_modules\async\lib\asyn
c.js:157:25
    at C:\Users\dmitry\AppData\Roaming\npm\node_modules\webgl-workshop\node_modules\inquirer\node_modules\async\lib\asyn
c.js:251:21

C:\Users\dmitry\Dropbox\Projects\gl-experiment\webgl-workshop-test>
```
