### ISSUE TITLE
 Cannot find module '@workshop/server'

### ISSUE THREAD

**Issue by crowne** [stackgl/webgl-workshop#89]
Hi,

I installed as per the README.md instructions and ran webgl-workshop which gave the following error:

Error: Cannot find module '@workshop/server'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at boot (C:\Users\crowne\AppData\Roaming\npm\node_modules\webgl-workshop\node.js:49:3)
    at PromptUI.completed (C:\Users\crowne\AppData\Roaming\npm\node_modules\webgl-workshop\node.js:44:5)
    at PromptUI.onCompletion (C:\Users\crowne\AppData\Roaming\npm\node_modules\webgl-workshop\node_modules\inquirer\lib\ui\prompt.js:51:10)
    at C:\Users\crowne\AppData\Roaming\npm\node_modules\webgl-workshop\node_modules\inquirer\node_modules\async\lib\async.js:254:17
    at C:\Users\crowne\AppData\Roaming\npm\node_modules\webgl-workshop\node_modules\inquirer\node_modules\async\lib\async.js:157:25
    at C:\Users\crowne\AppData\Roaming\npm\node_modules\webgl-workshop\node_modules\inquirer\node_modules\async\lib\async.js:251:21

**Comment by andyearnshaw** [comment]
Something changed in Node 5.x that broke webgl-workshop.  If you use _nvm_, `nvm install 4 && npm install -g webgl-workshop`.  Everything should work then.

**Comment by thatmichaelpark** [comment]
What if you don't use nvm?

And Node is now at 6 and counting; shouldn't someone just fix the actual problem?

**Comment by andyearnshaw** [comment]
Someone _should_ fix the actual problem.  In the meantime, there's a workaround.

**Comment by Jornason** [comment]
@andyearnshaw I've got same problem, according to your suggestion I installed nvm and press "nvm install 4 && npm install -g webgl-workshop", It works! Thanks a lot.

**Comment by Ninerian** [comment]
It seems, the subfolder work-shop and exercises are not installed. I cloned the repo and linked the start file to the bin folder.

**Comment by bmsdave** [comment]
Same issue.
```
λ npm -v
5.3.0

λ node -v
v6.9.1

λ uname
MSYS_NT-10.0
```

error:
```
readline.js:982
            throw err;
            ^

Error: Cannot find module '@workshop/server'
    at Function.Module._resolveFilename (module.js:469:15)
```

**Comment by PaulineStich** [comment]
I've got the same problem here..

**Comment by Mark2xv** [comment]
@RamonGebben Could you please look at this

**Comment by hbbdmc** [comment]
I've got the same problem too.......How to solve it on Windows
