### ISSUE TITLE
ReferenceError: primordials is not defined

### ISSUE THREAD

**Issue by Xresolver** [stackgl/webgl-workshop#95]
For the first time when I typed y, I got this error:
```
[?] We're about to populate this directory with some code for you to use for
    your answers. If they've already been created then don't worry, they won't
    be replaced. Continue? Yes

node:internal/readline/emitKeypressEvents:74
            throw err;
            ^

ReferenceError: primordials is not defined
    at fs.js:43:5
    at req_ (C:\Users\bilal\AppData\Roaming\npm\node_modules\webgl-workshop\node_modules\natives\index.js:143:24)
    at Object.req [as require] (C:\Users\bilal\AppData\Roaming\npm\node_modules\webgl-workshop\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (C:\Users\bilal\AppData\Roaming\npm\node_modules\webgl-workshop\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)

Node.js v20.11.1
```

**Comment by dhritzkiv** [comment]
The issue was with an outdated dependency. You see, this repository hasn't been updated in 8+ years, and many of its dependencies are stuck in time and at least one no longer works with modern node.

I pushed a change (1d40127fdbf3449144a409cb6a04aac2f92da452) that fixes this.

Unfortunately, I don't personally have the ability to publish this change to npm. What I would recommend in the meantime is to clone this repository locally, run `npm install`, then run `npm run start`. Then it should work for you.

Have fun!
